server:
  port: 8083

spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        static:
          access-key: test
          secret-key: test
      # Estrutura exata aceita pela autoconfiguração do Starter v3.3.x
      sqs:
        endpoint: http://localhost:4566
      dynamodb:
        table: Pessoa
        endpoint: http://localhost:4566

app:
  storage:
    s3:
      bucket: pessoa-s3-local
      #endpoint: http://localhost:4566
      endpoint: http://s3.localhost.localstack.cloud:4566
      region: us-east-1
      access-key: test
      secret-key: test
      path-style-access: true

---
spring:
  config:
    activate:
      on-profile: aws
  cloud:
    aws:
      region:
        static: us-east-1
      dynamodb:
        table: Pessoa

app:
  storage:
    s3:
      bucket: pessoa-s3-aws
      region: us-east-1
      path-style-access: false